name: Build, Test and Release

on:
  push:
    branches: [ master, dev ]
    pull_request: [ master, dev ]

jobs:
  test:
    runs-on: windows-latest
    name: Build and Test
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Setup nuget (required by XrmMockup)
        uses: nuget/setup-nuget@v1.0.2

      - name: Run tests
        run: ./build.cmd test

      - name: Pack package
        run: dotnet pack src\\XrmMockup365\\XrmMockup365.csproj -o artifacts
        
      - name: Publish package
        run: dotnet nuget push artifacts\\XrmMockup365*.nupkg --source https://nuget.pkg.github.com/thygesteffensen/index.json --api-key $env:GH_TOKEN"